# coding: utf-8

"""
    Studio API

    Studio API  # noqa: E501

    OpenAPI spec version: 1.6.2 
    Contact: support@deepopinion.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.reset_password_send_input import ResetPasswordSendInput  # noqa: E501
from swagger_client.rest import ApiException


class TestResetPasswordSendInput(unittest.TestCase):
    """ResetPasswordSendInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResetPasswordSendInput(self):
        """Test ResetPasswordSendInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.reset_password_send_input.ResetPasswordSendInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
