# coding: utf-8

"""
    Studio API

    Studio API  # noqa: E501

    OpenAPI spec version: 1.6.2 
    Contact: support@deepopinion.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.confirm_correction_tag import ConfirmCorrectionTag  # noqa: E501
from swagger_client.rest import ApiException


class TestConfirmCorrectionTag(unittest.TestCase):
    """ConfirmCorrectionTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfirmCorrectionTag(self):
        """Test ConfirmCorrectionTag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.confirm_correction_tag.ConfirmCorrectionTag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
