# coding: utf-8

"""
    Studio API

    Studio API  # noqa: E501

    OpenAPI spec version: 1.6.2 
    Contact: support@deepopinion.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.groups_api import GroupsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.groups_api.GroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_projects_project_id_groups_get(self):
        """Test case for projects_project_id_groups_get

        List all document groups that belongs to a project  # noqa: E501
        """
        pass

    def test_projects_project_id_groups_group_id_delete(self):
        """Test case for projects_project_id_groups_group_id_delete

        Delete a group of documents.  # noqa: E501
        """
        pass

    def test_projects_project_id_groups_group_id_documents_document_id_get(self):
        """Test case for projects_project_id_groups_group_id_documents_document_id_get

        Get a particular document of a group.  # noqa: E501
        """
        pass

    def test_projects_project_id_groups_group_id_documents_get(self):
        """Test case for projects_project_id_groups_group_id_documents_get

        Get documents of a group  # noqa: E501
        """
        pass

    def test_projects_project_id_groups_group_id_download_get(self):
        """Test case for projects_project_id_groups_group_id_download_get

        Download all the documents of a group  # noqa: E501
        """
        pass

    def test_projects_project_id_groups_group_id_get(self):
        """Test case for projects_project_id_groups_group_id_get

        Get a Document Group  # noqa: E501
        """
        pass

    def test_projects_project_id_groups_group_id_put(self):
        """Test case for projects_project_id_groups_group_id_put

        Change a document group.  # noqa: E501
        """
        pass

    def test_projects_project_id_groups_post(self):
        """Test case for projects_project_id_groups_post

        Create a new document group.  # noqa: E501
        """
        pass

    def test_projects_project_id_groups_upload_post(self):
        """Test case for projects_project_id_groups_upload_post

        Upload a file to a project. A file contains one or more documents that can  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
