# coding: utf-8

"""
    Studio API

    Studio API  # noqa: E501

    OpenAPI spec version: 1.6.2 
    Contact: support@deepopinion.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.users_api import UsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auth_login_post(self):
        """Test case for auth_login_post

        Log in a user  # noqa: E501
        """
        pass

    def test_auth_logout_post(self):
        """Test case for auth_logout_post

        Log out a user.  # noqa: E501
        """
        pass

    def test_auth_register_post(self):
        """Test case for auth_register_post

        Create a new account.  # noqa: E501
        """
        pass

    def test_auth_status_get(self):
        """Test case for auth_status_get

        User login status  # noqa: E501
        """
        pass

    def test_password_email_post(self):
        """Test case for password_email_post

        Request a link to reset the password.  # noqa: E501
        """
        pass

    def test_password_reset_post(self):
        """Test case for password_reset_post

        Reset a password.  # noqa: E501
        """
        pass

    def test_users_email_verify_post(self):
        """Test case for users_email_verify_post

        Confirm an email  # noqa: E501
        """
        pass

    def test_users_email_verify_resend_post(self):
        """Test case for users_email_verify_resend_post

        Resend verification email  # noqa: E501
        """
        pass

    def test_users_user_id_delete(self):
        """Test case for users_user_id_delete

        Delete user's account.  # noqa: E501
        """
        pass

    def test_users_user_id_get(self):
        """Test case for users_user_id_get

        Get a user.  # noqa: E501
        """
        pass

    def test_users_user_id_keys_get(self):
        """Test case for users_user_id_keys_get

        List all keys associated to a user  # noqa: E501
        """
        pass

    def test_users_user_id_keys_key_id_delete(self):
        """Test case for users_user_id_keys_key_id_delete

        Delete a key associated to a user  # noqa: E501
        """
        pass

    def test_users_user_id_keys_post(self):
        """Test case for users_user_id_keys_post

        Add a product key to a user  # noqa: E501
        """
        pass

    def test_users_user_id_permissions_get(self):
        """Test case for users_user_id_permissions_get

        Get user permissions.  # noqa: E501
        """
        pass

    def test_users_user_id_permissions_put(self):
        """Test case for users_user_id_permissions_put

        Change user permission.  # noqa: E501
        """
        pass

    def test_users_user_id_put(self):
        """Test case for users_user_id_put

        Change a user.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
