# coding: utf-8

"""
    Studio API

    Studio API  # noqa: E501

    OpenAPI spec version: 1.6.2 
    Contact: support@deepopinion.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.types import Types  # noqa: E501
from swagger_client.rest import ApiException


class TestTypes(unittest.TestCase):
    """Types unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypes(self):
        """Test Types"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.types.Types()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
