# coding: utf-8

"""
    Studio API

    Studio API  # noqa: E501

    OpenAPI spec version: 1.6.2 
    Contact: support@deepopinion.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.notifications_api import NotificationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.notifications_api.NotificationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_user_id_notifications_get(self):
        """Test case for users_user_id_notifications_get

        Get all user's notification  # noqa: E501
        """
        pass

    def test_users_user_id_notifications_notification_id_get(self):
        """Test case for users_user_id_notifications_notification_id_get

        Get a notification  # noqa: E501
        """
        pass

    def test_users_user_id_notifications_notification_id_put(self):
        """Test case for users_user_id_notifications_notification_id_put

        Change a notification  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
