# coding: utf-8

"""
    Studio API

    Studio API  # noqa: E501

    OpenAPI spec version: 1.6.2 
    Contact: support@deepopinion.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.models_api import ModelsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestModelsApi(unittest.TestCase):
    """ModelsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.models_api.ModelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_models_get(self):
        """Test case for models_get

        Get models user is authorized to see.  # noqa: E501
        """
        pass

    def test_models_model_download_get(self):
        """Test case for models_model_download_get

        Download a model by name  # noqa: E501
        """
        pass

    def test_models_model_id_analyses_get(self):
        """Test case for models_model_id_analyses_get

        Fetches all analyses related to this model.  # noqa: E501
        """
        pass

    def test_models_model_id_delete(self):
        """Test case for models_model_id_delete

        Delete a model.  # noqa: E501
        """
        pass

    def test_models_model_id_download_get(self):
        """Test case for models_model_id_download_get

        Download a model  # noqa: E501
        """
        pass

    def test_models_model_id_get(self):
        """Test case for models_model_id_get

        Get a model by its ID  # noqa: E501
        """
        pass

    def test_models_model_id_permissions_get(self):
        """Test case for models_model_id_permissions_get

        Get all model's permission.  # noqa: E501
        """
        pass

    def test_models_model_id_put(self):
        """Test case for models_model_id_put

        Update a model.  # noqa: E501
        """
        pass

    def test_models_model_id_star_post(self):
        """Test case for models_model_id_star_post

        Favorite a model.  # noqa: E501
        """
        pass

    def test_models_model_id_unstar_post(self):
        """Test case for models_model_id_unstar_post

        Remove a model from favorites.  # noqa: E501
        """
        pass

    def test_models_upload_post(self):
        """Test case for models_upload_post

        Upload a model.  # noqa: E501
        """
        pass

    def test_organizations_organization_models_get(self):
        """Test case for organizations_organization_models_get

        Get models user is authorized to see.  # noqa: E501
        """
        pass

    def test_organizations_organization_models_model_download_get(self):
        """Test case for organizations_organization_models_model_download_get

        Download a model by organization name and model name  # noqa: E501
        """
        pass

    def test_projects_project_id_models_get(self):
        """Test case for projects_project_id_models_get

        Get models that belongs to a project  # noqa: E501
        """
        pass

    def test_projects_project_id_models_model_id_delete(self):
        """Test case for projects_project_id_models_model_id_delete

        Delete a model that belongs to a project..  # noqa: E501
        """
        pass

    def test_projects_project_id_models_model_id_download_get(self):
        """Test case for projects_project_id_models_model_id_download_get

        Download a model that belongs to a project  # noqa: E501
        """
        pass

    def test_projects_project_id_models_model_id_get(self):
        """Test case for projects_project_id_models_model_id_get

        Get a specific model that belongs to a project  # noqa: E501
        """
        pass

    def test_projects_project_id_models_model_id_put(self):
        """Test case for projects_project_id_models_model_id_put

        Update a model that belongs to a project.  # noqa: E501
        """
        pass

    def test_projects_project_id_models_post(self):
        """Test case for projects_project_id_models_post

        Train a new model.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
