# coding: utf-8

"""
    Studio API

    Studio API  # noqa: E501

    OpenAPI spec version: 1.6.2 
    Contact: support@deepopinion.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.types_api import TypesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTypesApi(unittest.TestCase):
    """TypesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.types_api.TypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_types_get(self):
        """Test case for types_get

        List all available task types  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
