# coding: utf-8

"""
    Studio API

    Studio API  # noqa: E501

    OpenAPI spec version: 1.6.2 
    Contact: support@deepopinion.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.classes_api import ClassesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClassesApi(unittest.TestCase):
    """ClassesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.classes_api.ClassesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_projects_project_id_classes_class_id_delete(self):
        """Test case for projects_project_id_classes_class_id_delete

        Delete a class  # noqa: E501
        """
        pass

    def test_projects_project_id_classes_class_id_get(self):
        """Test case for projects_project_id_classes_class_id_get

        Get a class  # noqa: E501
        """
        pass

    def test_projects_project_id_classes_class_id_put(self):
        """Test case for projects_project_id_classes_class_id_put

        Change class's data  # noqa: E501
        """
        pass

    def test_projects_project_id_classes_download_get(self):
        """Test case for projects_project_id_classes_download_get

        Download all project's classes  # noqa: E501
        """
        pass

    def test_projects_project_id_classes_get(self):
        """Test case for projects_project_id_classes_get

        Get all project's classes  # noqa: E501
        """
        pass

    def test_projects_project_id_classes_post(self):
        """Test case for projects_project_id_classes_post

        Add a new class to a project  # noqa: E501
        """
        pass

    def test_projects_project_id_classes_upload_post(self):
        """Test case for projects_project_id_classes_upload_post

        Upload a file containing classes definition.  # noqa: E501
        """
        pass

    def test_projects_project_id_upload_classes_post(self):
        """Test case for projects_project_id_upload_classes_post

        Add multiple classes to a project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
