# coding: utf-8

# flake8: noqa

"""
    Studio API

    Studio API  # noqa: E501

    OpenAPI spec version: 1.6.2 
    Contact: support@deepopinion.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.analyses_api import AnalysesApi
from swagger_client.api.classes_api import ClassesApi
from swagger_client.api.correction_api import CorrectionApi
from swagger_client.api.documents_api import DocumentsApi
from swagger_client.api.groups_api import GroupsApi
from swagger_client.api.labeling_api import LabelingApi
from swagger_client.api.labels_api import LabelsApi
from swagger_client.api.models_api import ModelsApi
from swagger_client.api.monitoring_api import MonitoringApi
from swagger_client.api.notifications_api import NotificationsApi
from swagger_client.api.projects_api import ProjectsApi
from swagger_client.api.types_api import TypesApi
from swagger_client.api.users_api import UsersApi
from swagger_client.api.workspaces_api import WorkspacesApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.accept_invitation_input import AcceptInvitationInput
from swagger_client.models.ad_hoc_analysis import AdHocAnalysis
from swagger_client.models.ad_hoc_analysis_create import AdHocAnalysisCreate
from swagger_client.models.analyses import Analyses
from swagger_client.models.analysis import Analysis
from swagger_client.models.analysis_create import AnalysisCreate
from swagger_client.models.annotate_correction_response import AnnotateCorrectionResponse
from swagger_client.models.body import Body
from swagger_client.models.body1 import Body1
from swagger_client.models.body2 import Body2
from swagger_client.models.body3 import Body3
from swagger_client.models.body4 import Body4
from swagger_client.models.body5 import Body5
from swagger_client.models.body6 import Body6
from swagger_client.models.body7 import Body7
from swagger_client.models.change_annotation_tag import ChangeAnnotationTag
from swagger_client.models.change_permission_body import ChangePermissionBody
from swagger_client.models.class_label_tag import ClassLabelTag
from swagger_client.models.class_label_tags import ClassLabelTags
from swagger_client.models.class_tag import ClassTag
from swagger_client.models.classes import Classes
from swagger_client.models.confirm_correction_tag import ConfirmCorrectionTag
from swagger_client.models.confirm_user_email import ConfirmUserEmail
from swagger_client.models.correction import Correction
from swagger_client.models.correction_create import CorrectionCreate
from swagger_client.models.correction_model import CorrectionModel
from swagger_client.models.corrections import Corrections
from swagger_client.models.create_correction_tag_response import CreateCorrectionTagResponse
from swagger_client.models.create_correction_tag_response_segment import CreateCorrectionTagResponseSegment
from swagger_client.models.create_workspace_input import CreateWorkspaceInput
from swagger_client.models.detailed_model import DetailedModel
from swagger_client.models.document import Document
from swagger_client.models.document_annotation_status import DocumentAnnotationStatus
from swagger_client.models.document_change_input import DocumentChangeInput
from swagger_client.models.document_create import DocumentCreate
from swagger_client.models.document_create_segments import DocumentCreateSegments
from swagger_client.models.document_group import DocumentGroup
from swagger_client.models.document_group_change import DocumentGroupChange
from swagger_client.models.document_groups import DocumentGroups
from swagger_client.models.documents_segments import DocumentsSegments
from swagger_client.models.documents_segments_response import DocumentsSegmentsResponse
from swagger_client.models.file_preview import FilePreview
from swagger_client.models.get_analyses import GetAnalyses
from swagger_client.models.get_models import GetModels
from swagger_client.models.group_create import GroupCreate
from swagger_client.models.invitation import Invitation
from swagger_client.models.invitations import Invitations
from swagger_client.models.invite_users_body import InviteUsersBody
from swagger_client.models.invite_users_response import InviteUsersResponse
from swagger_client.models.invite_users_response_not_invited import InviteUsersResponseNotInvited
from swagger_client.models.label import Label
from swagger_client.models.label_input import LabelInput
from swagger_client.models.label_tag import LabelTag
from swagger_client.models.labeling_session import LabelingSession
from swagger_client.models.labeling_session_change import LabelingSessionChange
from swagger_client.models.labeling_session_create import LabelingSessionCreate
from swagger_client.models.labeling_session_with_docs import LabelingSessionWithDocs
from swagger_client.models.labeling_sessions import LabelingSessions
from swagger_client.models.labelled_document import LabelledDocument
from swagger_client.models.labelled_documents import LabelledDocuments
from swagger_client.models.labelled_documents_response import LabelledDocumentsResponse
from swagger_client.models.labels_response import LabelsResponse
from swagger_client.models.login_response import LoginResponse
from swagger_client.models.model import Model
from swagger_client.models.model_class import ModelClass
from swagger_client.models.model_create import ModelCreate
from swagger_client.models.model_permission import ModelPermission
from swagger_client.models.model_permissions import ModelPermissions
from swagger_client.models.models import Models
from swagger_client.models.notification import Notification
from swagger_client.models.notification_input import NotificationInput
from swagger_client.models.notifications import Notifications
from swagger_client.models.permission import Permission
from swagger_client.models.permission_input import PermissionInput
from swagger_client.models.permissions import Permissions
from swagger_client.models.product_key import ProductKey
from swagger_client.models.product_keys import ProductKeys
from swagger_client.models.project import Project
from swagger_client.models.project_permission import ProjectPermission
from swagger_client.models.project_permissions import ProjectPermissions
from swagger_client.models.project_tags_response import ProjectTagsResponse
from swagger_client.models.projects import Projects
from swagger_client.models.registration_response import RegistrationResponse
from swagger_client.models.reset_password_input import ResetPasswordInput
from swagger_client.models.reset_password_send_input import ResetPasswordSendInput
from swagger_client.models.segment import Segment
from swagger_client.models.segment_annotation_status import SegmentAnnotationStatus
from swagger_client.models.segment_with_tags import SegmentWithTags
from swagger_client.models.set_default_body import SetDefaultBody
from swagger_client.models.type import Type
from swagger_client.models.types import Types
from swagger_client.models.upload_documents import UploadDocuments
from swagger_client.models.user import User
from swagger_client.models.user_login import UserLogin
from swagger_client.models.user_permission import UserPermission
from swagger_client.models.users import Users
from swagger_client.models.workspace import Workspace
