# coding: utf-8

"""
    Studio API

    Studio API  # noqa: E501

    OpenAPI spec version: 1.6.2 
    Contact: support@deepopinion.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class CorrectionCreate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'model_id': 'int',
        'name': 'str',
        'sample_size': 'int'
    }

    attribute_map = {
        'model_id': 'model_id',
        'name': 'name',
        'sample_size': 'sample_size'
    }

    def __init__(self, model_id=None, name=None, sample_size=None, _configuration=None):  # noqa: E501
        """CorrectionCreate - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._model_id = None
        self._name = None
        self._sample_size = None
        self.discriminator = None

        self.model_id = model_id
        if name is not None:
            self.name = name
        if sample_size is not None:
            self.sample_size = sample_size

    @property
    def model_id(self):
        """Gets the model_id of this CorrectionCreate.  # noqa: E501

        ID of the model  # noqa: E501

        :return: The model_id of this CorrectionCreate.  # noqa: E501
        :rtype: int
        """
        return self._model_id

    @model_id.setter
    def model_id(self, model_id):
        """Sets the model_id of this CorrectionCreate.

        ID of the model  # noqa: E501

        :param model_id: The model_id of this CorrectionCreate.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and model_id is None:
            raise ValueError("Invalid value for `model_id`, must not be `None`")  # noqa: E501

        self._model_id = model_id

    @property
    def name(self):
        """Gets the name of this CorrectionCreate.  # noqa: E501

        Name of the correction session  # noqa: E501

        :return: The name of this CorrectionCreate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CorrectionCreate.

        Name of the correction session  # noqa: E501

        :param name: The name of this CorrectionCreate.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def sample_size(self):
        """Gets the sample_size of this CorrectionCreate.  # noqa: E501

        Sample size  # noqa: E501

        :return: The sample_size of this CorrectionCreate.  # noqa: E501
        :rtype: int
        """
        return self._sample_size

    @sample_size.setter
    def sample_size(self, sample_size):
        """Sets the sample_size of this CorrectionCreate.

        Sample size  # noqa: E501

        :param sample_size: The sample_size of this CorrectionCreate.  # noqa: E501
        :type: int
        """

        self._sample_size = sample_size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CorrectionCreate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CorrectionCreate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CorrectionCreate):
            return True

        return self.to_dict() != other.to_dict()
