# coding: utf-8

"""
    Studio API

    Studio API  # noqa: E501

    OpenAPI spec version: 1.6.2 
    Contact: support@deepopinion.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class DocumentGroupChange(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'document_ids': 'list[int]',
        'documents': 'list[DocumentGroup]',
        'name': 'str'
    }

    attribute_map = {
        'document_ids': 'document_ids',
        'documents': 'documents',
        'name': 'name'
    }

    def __init__(self, document_ids=None, documents=None, name=None, _configuration=None):  # noqa: E501
        """DocumentGroupChange - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._document_ids = None
        self._documents = None
        self._name = None
        self.discriminator = None

        if document_ids is not None:
            self.document_ids = document_ids
        if documents is not None:
            self.documents = documents
        if name is not None:
            self.name = name

    @property
    def document_ids(self):
        """Gets the document_ids of this DocumentGroupChange.  # noqa: E501

        IDs of documents that should be added to the group   # noqa: E501

        :return: The document_ids of this DocumentGroupChange.  # noqa: E501
        :rtype: list[int]
        """
        return self._document_ids

    @document_ids.setter
    def document_ids(self, document_ids):
        """Sets the document_ids of this DocumentGroupChange.

        IDs of documents that should be added to the group   # noqa: E501

        :param document_ids: The document_ids of this DocumentGroupChange.  # noqa: E501
        :type: list[int]
        """

        self._document_ids = document_ids

    @property
    def documents(self):
        """Gets the documents of this DocumentGroupChange.  # noqa: E501

        Documents that should be added to the group   # noqa: E501

        :return: The documents of this DocumentGroupChange.  # noqa: E501
        :rtype: list[DocumentGroup]
        """
        return self._documents

    @documents.setter
    def documents(self, documents):
        """Sets the documents of this DocumentGroupChange.

        Documents that should be added to the group   # noqa: E501

        :param documents: The documents of this DocumentGroupChange.  # noqa: E501
        :type: list[DocumentGroup]
        """

        self._documents = documents

    @property
    def name(self):
        """Gets the name of this DocumentGroupChange.  # noqa: E501

        The document group's name.  # noqa: E501

        :return: The name of this DocumentGroupChange.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DocumentGroupChange.

        The document group's name.  # noqa: E501

        :param name: The name of this DocumentGroupChange.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocumentGroupChange, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocumentGroupChange):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DocumentGroupChange):
            return True

        return self.to_dict() != other.to_dict()
