# coding: utf-8

"""
    Studio API

    Studio API  # noqa: E501

    OpenAPI spec version: 1.6.2 
    Contact: support@deepopinion.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class LabelingSession(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'classes': 'list[str]',
        'created': 'datetime',
        'description': 'str',
        'document_count': 'int',
        'document_group_id': 'int',
        'finished': 'datetime',
        'id': 'int',
        'labels': 'list[str]',
        'mode': 'str',
        'model_id': 'int',
        'name': 'str',
        'organization_id': 'int',
        'progress': 'float',
        'project_id': 'int',
        'status': 'str',
        'type': 'str',
        'user_id': 'int',
        'uuid': 'str'
    }

    attribute_map = {
        'classes': 'classes',
        'created': 'created',
        'description': 'description',
        'document_count': 'document_count',
        'document_group_id': 'document_group_id',
        'finished': 'finished',
        'id': 'id',
        'labels': 'labels',
        'mode': 'mode',
        'model_id': 'model_id',
        'name': 'name',
        'organization_id': 'organization_id',
        'progress': 'progress',
        'project_id': 'project_id',
        'status': 'status',
        'type': 'type',
        'user_id': 'user_id',
        'uuid': 'uuid'
    }

    def __init__(self, classes=None, created=None, description=None, document_count=None, document_group_id=None, finished=None, id=None, labels=None, mode=None, model_id=None, name=None, organization_id=None, progress=None, project_id=None, status=None, type=None, user_id=None, uuid=None, _configuration=None):  # noqa: E501
        """LabelingSession - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._classes = None
        self._created = None
        self._description = None
        self._document_count = None
        self._document_group_id = None
        self._finished = None
        self._id = None
        self._labels = None
        self._mode = None
        self._model_id = None
        self._name = None
        self._organization_id = None
        self._progress = None
        self._project_id = None
        self._status = None
        self._type = None
        self._user_id = None
        self._uuid = None
        self.discriminator = None

        if classes is not None:
            self.classes = classes
        if created is not None:
            self.created = created
        if description is not None:
            self.description = description
        if document_count is not None:
            self.document_count = document_count
        if document_group_id is not None:
            self.document_group_id = document_group_id
        if finished is not None:
            self.finished = finished
        if id is not None:
            self.id = id
        if labels is not None:
            self.labels = labels
        if mode is not None:
            self.mode = mode
        if model_id is not None:
            self.model_id = model_id
        if name is not None:
            self.name = name
        if organization_id is not None:
            self.organization_id = organization_id
        if progress is not None:
            self.progress = progress
        if project_id is not None:
            self.project_id = project_id
        if status is not None:
            self.status = status
        if type is not None:
            self.type = type
        if user_id is not None:
            self.user_id = user_id
        if uuid is not None:
            self.uuid = uuid

    @property
    def classes(self):
        """Gets the classes of this LabelingSession.  # noqa: E501

        All classes that belong to the session  # noqa: E501

        :return: The classes of this LabelingSession.  # noqa: E501
        :rtype: list[str]
        """
        return self._classes

    @classes.setter
    def classes(self, classes):
        """Sets the classes of this LabelingSession.

        All classes that belong to the session  # noqa: E501

        :param classes: The classes of this LabelingSession.  # noqa: E501
        :type: list[str]
        """

        self._classes = classes

    @property
    def created(self):
        """Gets the created of this LabelingSession.  # noqa: E501

        When the session was started.  # noqa: E501

        :return: The created of this LabelingSession.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this LabelingSession.

        When the session was started.  # noqa: E501

        :param created: The created of this LabelingSession.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def description(self):
        """Gets the description of this LabelingSession.  # noqa: E501

        The session's description.  # noqa: E501

        :return: The description of this LabelingSession.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this LabelingSession.

        The session's description.  # noqa: E501

        :param description: The description of this LabelingSession.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def document_count(self):
        """Gets the document_count of this LabelingSession.  # noqa: E501

        Total of documents  # noqa: E501

        :return: The document_count of this LabelingSession.  # noqa: E501
        :rtype: int
        """
        return self._document_count

    @document_count.setter
    def document_count(self, document_count):
        """Sets the document_count of this LabelingSession.

        Total of documents  # noqa: E501

        :param document_count: The document_count of this LabelingSession.  # noqa: E501
        :type: int
        """

        self._document_count = document_count

    @property
    def document_group_id(self):
        """Gets the document_group_id of this LabelingSession.  # noqa: E501

        ID of the document group related to the session, if any  # noqa: E501

        :return: The document_group_id of this LabelingSession.  # noqa: E501
        :rtype: int
        """
        return self._document_group_id

    @document_group_id.setter
    def document_group_id(self, document_group_id):
        """Sets the document_group_id of this LabelingSession.

        ID of the document group related to the session, if any  # noqa: E501

        :param document_group_id: The document_group_id of this LabelingSession.  # noqa: E501
        :type: int
        """

        self._document_group_id = document_group_id

    @property
    def finished(self):
        """Gets the finished of this LabelingSession.  # noqa: E501

        When the session was finished.  # noqa: E501

        :return: The finished of this LabelingSession.  # noqa: E501
        :rtype: datetime
        """
        return self._finished

    @finished.setter
    def finished(self, finished):
        """Sets the finished of this LabelingSession.

        When the session was finished.  # noqa: E501

        :param finished: The finished of this LabelingSession.  # noqa: E501
        :type: datetime
        """

        self._finished = finished

    @property
    def id(self):
        """Gets the id of this LabelingSession.  # noqa: E501

        The ID of the session.  # noqa: E501

        :return: The id of this LabelingSession.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LabelingSession.

        The ID of the session.  # noqa: E501

        :param id: The id of this LabelingSession.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def labels(self):
        """Gets the labels of this LabelingSession.  # noqa: E501

        All labels that belong to the session  # noqa: E501

        :return: The labels of this LabelingSession.  # noqa: E501
        :rtype: list[str]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this LabelingSession.

        All labels that belong to the session  # noqa: E501

        :param labels: The labels of this LabelingSession.  # noqa: E501
        :type: list[str]
        """

        self._labels = labels

    @property
    def mode(self):
        """Gets the mode of this LabelingSession.  # noqa: E501

        The session's mode.  # noqa: E501

        :return: The mode of this LabelingSession.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this LabelingSession.

        The session's mode.  # noqa: E501

        :param mode: The mode of this LabelingSession.  # noqa: E501
        :type: str
        """
        allowed_values = ["ANNOTATION", "CORRECTION"]  # noqa: E501
        if (self._configuration.client_side_validation and
                mode not in allowed_values):
            raise ValueError(
                "Invalid value for `mode` ({0}), must be one of {1}"  # noqa: E501
                .format(mode, allowed_values)
            )

        self._mode = mode

    @property
    def model_id(self):
        """Gets the model_id of this LabelingSession.  # noqa: E501

        The ID of the model used by that session. This property only makes sense for correction sessions  # noqa: E501

        :return: The model_id of this LabelingSession.  # noqa: E501
        :rtype: int
        """
        return self._model_id

    @model_id.setter
    def model_id(self, model_id):
        """Sets the model_id of this LabelingSession.

        The ID of the model used by that session. This property only makes sense for correction sessions  # noqa: E501

        :param model_id: The model_id of this LabelingSession.  # noqa: E501
        :type: int
        """

        self._model_id = model_id

    @property
    def name(self):
        """Gets the name of this LabelingSession.  # noqa: E501

        The session's name.  # noqa: E501

        :return: The name of this LabelingSession.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this LabelingSession.

        The session's name.  # noqa: E501

        :param name: The name of this LabelingSession.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def organization_id(self):
        """Gets the organization_id of this LabelingSession.  # noqa: E501

        ID of the organization to which the session belongs.  # noqa: E501

        :return: The organization_id of this LabelingSession.  # noqa: E501
        :rtype: int
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this LabelingSession.

        ID of the organization to which the session belongs.  # noqa: E501

        :param organization_id: The organization_id of this LabelingSession.  # noqa: E501
        :type: int
        """

        self._organization_id = organization_id

    @property
    def progress(self):
        """Gets the progress of this LabelingSession.  # noqa: E501

        The session's progress.  # noqa: E501

        :return: The progress of this LabelingSession.  # noqa: E501
        :rtype: float
        """
        return self._progress

    @progress.setter
    def progress(self, progress):
        """Sets the progress of this LabelingSession.

        The session's progress.  # noqa: E501

        :param progress: The progress of this LabelingSession.  # noqa: E501
        :type: float
        """

        self._progress = progress

    @property
    def project_id(self):
        """Gets the project_id of this LabelingSession.  # noqa: E501

        ID of the project to which the session belongs.  # noqa: E501

        :return: The project_id of this LabelingSession.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this LabelingSession.

        ID of the project to which the session belongs.  # noqa: E501

        :param project_id: The project_id of this LabelingSession.  # noqa: E501
        :type: int
        """

        self._project_id = project_id

    @property
    def status(self):
        """Gets the status of this LabelingSession.  # noqa: E501

        The session's status.  # noqa: E501

        :return: The status of this LabelingSession.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this LabelingSession.

        The session's status.  # noqa: E501

        :param status: The status of this LabelingSession.  # noqa: E501
        :type: str
        """
        allowed_values = ["CREATED", "STARTED", "ANNOTATING", "FAILED", "FINISHED", "SAMPLING", "PREDICTING", "DELETING"]  # noqa: E501
        if (self._configuration.client_side_validation and
                status not in allowed_values):
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def type(self):
        """Gets the type of this LabelingSession.  # noqa: E501

        The session's classification type.  # noqa: E501

        :return: The type of this LabelingSession.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this LabelingSession.

        The session's classification type.  # noqa: E501

        :param type: The type of this LabelingSession.  # noqa: E501
        :type: str
        """
        allowed_values = ["ABSA", "CLASS", "LABEL", "CLASSLABEL"]  # noqa: E501
        if (self._configuration.client_side_validation and
                type not in allowed_values):
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def user_id(self):
        """Gets the user_id of this LabelingSession.  # noqa: E501

        ID of the user to which the session belongs.  # noqa: E501

        :return: The user_id of this LabelingSession.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this LabelingSession.

        ID of the user to which the session belongs.  # noqa: E501

        :param user_id: The user_id of this LabelingSession.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def uuid(self):
        """Gets the uuid of this LabelingSession.  # noqa: E501

        The unique ID of the session.  # noqa: E501

        :return: The uuid of this LabelingSession.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this LabelingSession.

        The unique ID of the session.  # noqa: E501

        :param uuid: The uuid of this LabelingSession.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LabelingSession, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LabelingSession):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, LabelingSession):
            return True

        return self.to_dict() != other.to_dict()
