# coding: utf-8

"""
    Studio API

    Studio API  # noqa: E501

    OpenAPI spec version: 1.6.2 
    Contact: support@deepopinion.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Project(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'classes': 'list[str]',
        'created': 'datetime',
        'id': 'int',
        'labels': 'list[str]',
        'models': 'list[Model]',
        'name': 'str',
        'status': 'str',
        'type': 'str'
    }

    attribute_map = {
        'classes': 'classes',
        'created': 'created',
        'id': 'id',
        'labels': 'labels',
        'models': 'models',
        'name': 'name',
        'status': 'status',
        'type': 'type'
    }

    def __init__(self, classes=None, created=None, id=None, labels=None, models=None, name=None, status=None, type=None, _configuration=None):  # noqa: E501
        """Project - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._classes = None
        self._created = None
        self._id = None
        self._labels = None
        self._models = None
        self._name = None
        self._status = None
        self._type = None
        self.discriminator = None

        if classes is not None:
            self.classes = classes
        if created is not None:
            self.created = created
        if id is not None:
            self.id = id
        if labels is not None:
            self.labels = labels
        if models is not None:
            self.models = models
        if name is not None:
            self.name = name
        if status is not None:
            self.status = status
        if type is not None:
            self.type = type

    @property
    def classes(self):
        """Gets the classes of this Project.  # noqa: E501

        All classes that belong to the project  # noqa: E501

        :return: The classes of this Project.  # noqa: E501
        :rtype: list[str]
        """
        return self._classes

    @classes.setter
    def classes(self, classes):
        """Sets the classes of this Project.

        All classes that belong to the project  # noqa: E501

        :param classes: The classes of this Project.  # noqa: E501
        :type: list[str]
        """

        self._classes = classes

    @property
    def created(self):
        """Gets the created of this Project.  # noqa: E501


        :return: The created of this Project.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Project.


        :param created: The created of this Project.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def id(self):
        """Gets the id of this Project.  # noqa: E501

        The ID of the project.  # noqa: E501

        :return: The id of this Project.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Project.

        The ID of the project.  # noqa: E501

        :param id: The id of this Project.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def labels(self):
        """Gets the labels of this Project.  # noqa: E501

        All labels that belong to the project  # noqa: E501

        :return: The labels of this Project.  # noqa: E501
        :rtype: list[str]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this Project.

        All labels that belong to the project  # noqa: E501

        :param labels: The labels of this Project.  # noqa: E501
        :type: list[str]
        """

        self._labels = labels

    @property
    def models(self):
        """Gets the models of this Project.  # noqa: E501


        :return: The models of this Project.  # noqa: E501
        :rtype: list[Model]
        """
        return self._models

    @models.setter
    def models(self, models):
        """Sets the models of this Project.


        :param models: The models of this Project.  # noqa: E501
        :type: list[Model]
        """

        self._models = models

    @property
    def name(self):
        """Gets the name of this Project.  # noqa: E501

        The project's name.  # noqa: E501

        :return: The name of this Project.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Project.

        The project's name.  # noqa: E501

        :param name: The name of this Project.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def status(self):
        """Gets the status of this Project.  # noqa: E501

        The project's status.  # noqa: E501

        :return: The status of this Project.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Project.

        The project's status.  # noqa: E501

        :param status: The status of this Project.  # noqa: E501
        :type: str
        """
        allowed_values = ["CREATED", "CLONING", "DELETED", "FAILED"]  # noqa: E501
        if (self._configuration.client_side_validation and
                status not in allowed_values):
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def type(self):
        """Gets the type of this Project.  # noqa: E501

        The project's classification type.  # noqa: E501

        :return: The type of this Project.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Project.

        The project's classification type.  # noqa: E501

        :param type: The type of this Project.  # noqa: E501
        :type: str
        """
        allowed_values = ["ABSA", "CLASS", "LABEL", "CLASSLABEL"]  # noqa: E501
        if (self._configuration.client_side_validation and
                type not in allowed_values):
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Project, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Project):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Project):
            return True

        return self.to_dict() != other.to_dict()
