# coding: utf-8

"""
    Studio API

    Studio API  # noqa: E501

    OpenAPI spec version: 1.6.2 
    Contact: support@deepopinion.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ProjectPermission(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'model': 'str',
        'role': 'str'
    }

    attribute_map = {
        'id': 'id',
        'model': 'model',
        'role': 'role'
    }

    def __init__(self, id=None, model=None, role=None, _configuration=None):  # noqa: E501
        """ProjectPermission - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._model = None
        self._role = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if model is not None:
            self.model = model
        if role is not None:
            self.role = role

    @property
    def id(self):
        """Gets the id of this ProjectPermission.  # noqa: E501

        The permission ID.  # noqa: E501

        :return: The id of this ProjectPermission.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProjectPermission.

        The permission ID.  # noqa: E501

        :param id: The id of this ProjectPermission.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def model(self):
        """Gets the model of this ProjectPermission.  # noqa: E501

        The name of the project.  # noqa: E501

        :return: The model of this ProjectPermission.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this ProjectPermission.

        The name of the project.  # noqa: E501

        :param model: The model of this ProjectPermission.  # noqa: E501
        :type: str
        """

        self._model = model

    @property
    def role(self):
        """Gets the role of this ProjectPermission.  # noqa: E501

        The role.  # noqa: E501

        :return: The role of this ProjectPermission.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this ProjectPermission.

        The role.  # noqa: E501

        :param role: The role of this ProjectPermission.  # noqa: E501
        :type: str
        """
        allowed_values = ["VIEWER", "ANNOTATOR", "MANAGER"]  # noqa: E501
        if (self._configuration.client_side_validation and
                role not in allowed_values):
            raise ValueError(
                "Invalid value for `role` ({0}), must be one of {1}"  # noqa: E501
                .format(role, allowed_values)
            )

        self._role = role

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectPermission, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectPermission):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectPermission):
            return True

        return self.to_dict() != other.to_dict()
