# coding: utf-8

"""
    Studio API

    Studio API  # noqa: E501

    OpenAPI spec version: 1.6.2 
    Contact: support@deepopinion.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class UserPermission(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_betauser': 'bool',
        'is_superuser': 'bool'
    }

    attribute_map = {
        'is_betauser': 'is_betauser',
        'is_superuser': 'is_superuser'
    }

    def __init__(self, is_betauser=None, is_superuser=None, _configuration=None):  # noqa: E501
        """UserPermission - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._is_betauser = None
        self._is_superuser = None
        self.discriminator = None

        if is_betauser is not None:
            self.is_betauser = is_betauser
        if is_superuser is not None:
            self.is_superuser = is_superuser

    @property
    def is_betauser(self):
        """Gets the is_betauser of this UserPermission.  # noqa: E501

        Beta User Status  # noqa: E501

        :return: The is_betauser of this UserPermission.  # noqa: E501
        :rtype: bool
        """
        return self._is_betauser

    @is_betauser.setter
    def is_betauser(self, is_betauser):
        """Sets the is_betauser of this UserPermission.

        Beta User Status  # noqa: E501

        :param is_betauser: The is_betauser of this UserPermission.  # noqa: E501
        :type: bool
        """

        self._is_betauser = is_betauser

    @property
    def is_superuser(self):
        """Gets the is_superuser of this UserPermission.  # noqa: E501

        Superuser Status  # noqa: E501

        :return: The is_superuser of this UserPermission.  # noqa: E501
        :rtype: bool
        """
        return self._is_superuser

    @is_superuser.setter
    def is_superuser(self, is_superuser):
        """Sets the is_superuser of this UserPermission.

        Superuser Status  # noqa: E501

        :param is_superuser: The is_superuser of this UserPermission.  # noqa: E501
        :type: bool
        """

        self._is_superuser = is_superuser

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserPermission, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserPermission):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserPermission):
            return True

        return self.to_dict() != other.to_dict()
